def main(*args) -> int:
    #raise Exception("testing exceptions")
    print(args)
    return 0